# Generated by Django 5.0.3 on 2024-10-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(upload_to='ressources/')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('note', 'Note'), ('td', 'TD')], max_length=100)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='Cours.cours')),
            ],
        ),
    ]
