# Generated by Django 5.0.3 on 2024-10-10 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='titre',
        ),
        migrations.AddField(
            model_name='cours',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
