# Generated by Django 5.0.3 on 2024-10-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='Photos',
            field=models.FileField(default=6, upload_to='./photos/'),
            preserve_default=False,
        ),
    ]
