# Generated by Django 5.0.3 on 2024-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0002_etudiant_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='Photos',
            field=models.FileField(blank=True, null=True, upload_to='./photos/'),
        ),
    ]
