# Generated by Django 5.0.3 on 2024-10-13 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0005_alter_etudiants_options_alter_etudiants_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etudiants',
            options={},
        ),
        migrations.AlterModelManagers(
            name='etudiants',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='etudiants',
            name='username',
        ),
    ]
