# Generated by Django 5.0.3 on 2024-10-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etudiants', '0006_alter_etudiants_options_alter_etudiants_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiants',
            name='nationalite',
            field=models.CharField(choices=[('CI', "Côte d'Ivoire"), ('BF', 'Burkina Faso'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('SN', 'Sénégal'), ('ML', 'Mali'), ('CM', 'Cameroun'), ('CM', 'Cameroun'), ('HA', 'Haïti')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
